export const REQUEST_DETAILS = 'REQUEST_DETAILS';
export const REQUEST_OFFER_RENT = 'REQUEST_OFFER_RENT';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_DELETE_INFO = 'REQUEST_DELETE_INFO';
export const REQUEST_GOOGLE_API_FIND_ADDRESS = 'REQUEST_GOOGLE_API_FIND_ADDRESS';
export const REQUEST_GOOGLE_API_GET_PROVINCE_LOCATION = 'REQUEST_GOOGLE_API_GET_PROVINCE_LOCATION';